
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2023.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2024 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_PIXEL_CTRL_DEVICE_ID,
		XPAR_PIXEL_CTRL_BASEADDR,
		XPAR_PIXEL_CTRL_INTERRUPT_PRESENT,
		XPAR_PIXEL_CTRL_IS_DUAL
	},
	{
		XPAR_RGBLEDS_GPIO_DEVICE_ID,
		XPAR_RGBLEDS_GPIO_BASEADDR,
		XPAR_RGBLEDS_GPIO_INTERRUPT_PRESENT,
		XPAR_RGBLEDS_GPIO_IS_DUAL
	},
	{
		XPAR_SWSLEDS_GPIO_DEVICE_ID,
		XPAR_SWSLEDS_GPIO_BASEADDR,
		XPAR_SWSLEDS_GPIO_INTERRUPT_PRESENT,
		XPAR_SWSLEDS_GPIO_IS_DUAL
	}
};


